extends RefCounted

func run() -> void:
	var protocol_source := FileAccess.get_file_as_string("res://scripts/network/poker_protocol.gd")
	assert(protocol_source.find("const START_AI_WARMUP := \"start_ai_warmup\"") != -1)
	assert(protocol_source.find("static func start_ai_warmup(room_id: String)") != -1)
	var client_source := FileAccess.get_file_as_string("res://scripts/network/poker_ws_client.gd")
	assert(client_source.find("signal start_ai_warmup_result_received") != -1)
	assert(client_source.find("func start_ai_warmup(target_room_id: String = room_id)") != -1)
	var table_source := FileAccess.get_file_as_string("res://scripts/screens/poker_table_screen.gd")
	assert(table_source.find("START AI WARM-UP clicked") != -1)
	assert(table_source.find("_poker_ws_client.start_ai_warmup(_server_room_id)") != -1)
	assert(table_source.find("_send_server_message(_poker_ws_client.start_ai_warmup(_server_room_id), \"start_ai_warmup %s\" % _server_room_id)") != -1)
	var warmup_func := table_source.find("func _start_public_ai_warmup()")
	var server_command := table_source.find("_poker_ws_client.start_ai_warmup(_server_room_id)", warmup_func)
	var local_warmup_fallback := table_source.find("_activate_public_warmup_ai_seats(3)", warmup_func)
	assert(warmup_func != -1 and server_command != -1 and local_warmup_fallback != -1)
	assert(server_command < local_warmup_fallback)
	assert(table_source.find("is_server_ai_warmup") != -1)
	assert(table_source.find("AI warm-up snapshot applied") != -1)
	var server_source := FileAccess.get_file_as_string("res://server/src/room_manager.ts")
	assert(server_source.find("start_ai_warmup_result") != -1)
	assert(server_source.find("real_player_count=${realCount}") != -1)
	assert(server_source.find("room.table.startHand()") != -1)
	assert(server_source.find("if (room.isAiWarmup) return;") != -1)
