const pages=[["dashboard","Dashboard"],["players","Players"],["transactions","Wallet Transactions"],["matches","Matches"],["replays","Replays"],["status","Server Status"],["audits","Audit Log"]];
const $=s=>document.querySelector(s),content=$("#content"); let currentPlayer=null,pending=null;
$("nav").innerHTML=pages.map(([id,n])=>`<button data-page="${id}">${n}</button>`).join("");
$("nav").onclick=e=>e.target.dataset.page&&load(e.target.dataset.page);
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/session",{method:"POST",body:JSON.stringify({pin:$("#pin").value})});$("#login").hidden=true;$("#app").hidden=false;load("dashboard")}catch(x){$("#loginError").textContent=x.message}};
$("#backup").onclick=async()=>{if(!confirm("确认使用固定目录创建 SQLite 在线备份？"))return;try{const x=await api("/api/backup",{method:"POST"});alert(`备份成功：${x.filename}`)}catch(x){alert(x.message)}};
async function load(page){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));$("#title").textContent=pages.find(x=>x[0]===page)?.[1]||page;content.innerHTML="<p>Loading…</p>";try{if(page==="dashboard")dashboard(await api("/api/dashboard"));else if(page==="players")players();else if(page==="status")object(await api("/api/server-status"));else objectTable(await api(`/api/${page}`));}catch(e){content.innerHTML=`<div class="panel bad">${esc(e.message)}</div>`}}
function dashboard(d){const metrics=[["数据库",d.database],["游戏服务",d.game_server.running?"运行中":"不可达"],["玩家",d.players],["24h 登录",d.active_24h],["Chip 总额",d.chips],["Gem 总额",d.gems],["对局",d.matches],["24h 对局",d.recent_matches],["Replay",d.replays],["Replay 解锁",d.unlocks]];content.innerHTML=`<div class="grid">${metrics.map(x=>`<div class="card"><div class="muted">${x[0]}</div><div class="metric">${esc(x[1])}</div></div>`).join("")}</div><h2 style="margin-top:26px">最近管理员操作</h2>${table(d.audits)}`}
function players(){content.innerHTML=`<div class="toolbar"><input id="search" placeholder="Player ID / Steam ID / 昵称"><button id="searchBtn">搜索</button></div><div id="playerResults"></div>`;$("#searchBtn").onclick=search;$("#search").onkeydown=e=>e.key==="Enter"&&search();search()}
async function search(){const rows=await api(`/api/players?q=${encodeURIComponent($("#search").value)}`);$("#playerResults").innerHTML=table(rows,true)}
content.onclick=e=>{const id=e.target.dataset.player;if(id)detail(id)}
async function detail(id){currentPlayer=id;const d=await api(`/api/players/${encodeURIComponent(id)}`);$("#title").textContent=`Player · ${d.display_name}`;content.innerHTML=`<div class="grid"><div class="card"><span class="muted">Player ID</span><pre>${esc(d.player_id)}</pre><span class="muted">Steam ID</span><pre>${esc(d.steam_id||"unavailable")}</pre></div><div class="card"><span class="muted">Chip / Gem</span><div class="metric">${d.chips} / ${d.gems}</div><span class="muted">XP / Level</span><div>${d.total_xp} / Lv.${d.level}</div></div><div class="card"><span class="muted">封禁状态</span><div class="${d.is_banned?"bad":"good"}">${d.is_banned?"已封禁":"正常"}</div><span class="muted">最后登录</span><div>${esc(d.last_login_at||"unavailable")}</div></div></div><div class="actions"><button data-act="chips">调整 Chip</button><button data-act="gems">调整 Gem</button><button data-act="xp">设置 XP</button><button data-act="daily_reset">重置 Daily Bonus</button><button class="danger" data-act="${d.is_banned?"unban":"ban"}">${d.is_banned?"解封":"封禁"}</button></div><div class="panel"><h2>管理员备注</h2><textarea id="note">${esc(d.admin_note)}</textarea><button id="saveNote">保存备注</button></div>${sections(d)}`;document.querySelector(".actions").onclick=e=>e.target.dataset.act&&openAction(e.target.dataset.act);$("#saveNote").onclick=()=>postAction({action:"note",note:$("#note").value,reason:"管理员备注更新"})}
function sections(d){return [["最近钱包流水",d.transactions],["最近对局",d.matches],["最近 Replay",d.replays],["Replay 解锁",d.unlocks],["Daily Bonus",d.daily_bonus],["管理员审计",d.audits]].map(x=>`<h2 style="margin-top:24px">${x[0]}</h2>${table(x[1])}`).join("")}
function openAction(act){pending=act;const noValue=["daily_reset","ban","unban"].includes(act);$("#actionTitle").textContent={chips:"调整 Chip（正数增加，负数扣除）",gems:"调整 Gem（正数增加，负数扣除）",xp:"设置 XP 总值",daily_reset:"重置全部 Daily Bonus 领取记录",ban:"封禁玩家",unban:"解封玩家"}[act];$("#actionValue").hidden=noValue;$("#actionValue").required=!noValue;$("#actionValue").value="";$("#actionReason").value="";$("#confirmCheck").checked=false;$("#actionDialog").showModal()}
$("#actionForm").onsubmit=async e=>{if(e.submitter.value==="cancel")return;e.preventDefault();const b={action:pending,reason:$("#actionReason").value};if(pending==="chips"||pending==="gems"){b.action="wallet";b.currency=pending;b.amount=Number($("#actionValue").value)}if(pending==="xp")b.value=Number($("#actionValue").value);await postAction(b);$("#actionDialog").close();detail(currentPlayer)}
async function postAction(body){try{return await api(`/api/players/${encodeURIComponent(currentPlayer)}`,{method:"POST",body:JSON.stringify(body)})}catch(e){alert(e.message);throw e}}
function object(x){content.innerHTML=`<div class="panel"><pre>${esc(JSON.stringify(x,null,2))}</pre></div>`}function objectTable(x){content.innerHTML=table(x)}
function table(rows,playerLinks=false){if(!rows?.length)return`<div class="panel muted">暂无数据 / unavailable</div>`;const cols=Object.keys(rows[0]);return`<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${playerLinks&&c==="player_id"?`<span class="link" data-player="${esc(r[c])}">${esc(r[c])}</span>`:esc(r[c])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});const x=await r.json();if(!r.ok)throw new Error(x.error||`HTTP ${r.status}`);return x}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
